-- AMORTIZE — ledger DDL.
-- Run with:  amort snowflake-init      (or paste into a Snowsight worksheet)
-- Idempotent except the SAVINGS view, which is CREATE OR REPLACE by design.

CREATE DATABASE IF NOT EXISTS AMORTIZE;
CREATE SCHEMA IF NOT EXISTS AMORTIZE.LEDGER;
USE SCHEMA AMORTIZE.LEDGER;

CREATE TABLE IF NOT EXISTS RUNS (
  RUN_ID STRING, TASK_FINGERPRINT STRING, LANE STRING, MODE STRING,
  MODEL STRING, STARTED_AT TIMESTAMP_NTZ, ENDED_AT TIMESTAMP_NTZ,
  WALL_MS NUMBER, LLM_CALLS NUMBER, TOOL_CALLS NUMBER,
  INPUT_TOKENS NUMBER, OUTPUT_TOKENS NUMBER, COST_USD FLOAT,
  SKILL_ID STRING, PARITY STRING, OUTPUT_HASH STRING
);

CREATE TABLE IF NOT EXISTS STEPS (
  RUN_ID STRING, STEP_IDX NUMBER, KIND STRING, NAME STRING, MODEL STRING,
  INPUT_TOKENS NUMBER, OUTPUT_TOKENS NUMBER, COST_USD FLOAT,
  WALL_MS NUMBER, TS TIMESTAMP_NTZ, META VARIANT
);

CREATE TABLE IF NOT EXISTS SKILLS (
  SKILL_ID STRING, TASK_FINGERPRINT STRING, STATUS STRING,      -- candidate|verified|trusted
  CREATED_AT TIMESTAMP_NTZ, RUNS_OBSERVED NUMBER, PARITY_RATE FLOAT,
  AVG_COLD_COST FLOAT, AVG_WARM_COST FLOAT, TOTAL_SAVED_USD FLOAT, MD_PATH STRING
);

CREATE OR REPLACE VIEW SAVINGS AS
SELECT TASK_FINGERPRINT,
       AVG(IFF(LANE='baseline', COST_USD, NULL))  AS AVG_BASELINE_COST,
       AVG(IFF(LANE='amortize' AND MODE='cold', COST_USD, NULL)) AS AVG_LIGHTENED_COST,
       AVG(IFF(LANE='amortize' AND MODE='warm', COST_USD, NULL)) AS AVG_WARM_COST,
       SUM(IFF(LANE='baseline', COST_USD, -COST_USD))            AS NET_SAVED_USD,
       COUNT(*) AS TOTAL_RUNS
FROM RUNS GROUP BY TASK_FINGERPRINT;
